<?php

namespace Woda\FSBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{

    /**
     * findByPath method
     *
     * Returns folder by its path. Returns rootfolder if path's wrong.
     */
    public function findByPath($path, $user)
    {
        if ($user === null)
            return null;

        $path = explode('/', $path);
        $folder = $this->findOneBy(array('user' => $user, 'parent' => null));

        foreach ($path as $fname) {
            if ($fname == '')
                continue;

            $folder = $this->findOneBy(array('user' => $user, 'parent' => $folder, 'name' => $fname));

            if ($folder === null) {
                break;
            }
        }

        return $folder;
    }

    public function search($user, $term, $order = array(), $limit = null)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM WodaFSBundle:Folder p where (p.public = true OR p.user = :owner) AND LOWER(p.name) like :name')
            ->setParameter('owner', $user)
            ->setParameter('name', '%'.strtolower($term).'%')
        ;
        $count = count(new Paginator($query, true));

        if (!empty($limit)) {
            if (is_array($limit) && count($limit) == 2) {
                $query->setFirstResult($limit[0]);
                $query->setMaxResults($limit[1]);
            } else if (is_int($limit)) {
                $query->setMaxResults($limit);
            }
        }

        $o = new \stdClass();
        $o->result = $query->getResult();
        $o->count = $count;

        return ($o);
    }
}