#WodaUIBundle:
#    resource: "@WodaUIBundle/Controller/"
#    type:     annotation
#    prefix:   /

WodaUserBundle:
    resource: "@WodaUserBundle/Controller/"
    type:     annotation
    prefix:   /

WodaAdministrationCmsBundle:
    resource: "@WodaAdministrationCmsBundle/Controller/"
    type:     annotation
    prefix:   /administration

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
