woda_search:
    resource: "@WodaSearchBundle/Controller/"
    type:     annotation
    prefix:   /

woda_fs:
    resource: "@WodaFSBundle/Controller/"
    type:     annotation
    prefix:   /

woda_server:
    resource: "@WodaServerBundle/Controller/"
    type:     annotation
    prefix:   /

wodaCmsBundle:
    resource: "@WodaCmsBundle/Controller/"
    type:     annotation
    prefix:   /

WodaAdminBundle:
    resource: "@WodaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

WodaUserBundle:
    resource: "@WodaUserBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
