jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Woda\UserBundle\Entity\User:
           id: woda.user.password_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        wodauserbundle:
            entity:
                class: WodaUserBundle:User
                property: login

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout: true
            form_login:
                provider: wodauserbundle
                login_path: WodaUserBundle.Security.login
                check_path: WodaUserBundle.Security.check
                default_target_path: WodaFSBundle.Default.list
            logout:
                path: WodaUserBundle.Security.logout

    access_control:

        # debug requirements
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt,      role: IS_AUTHENTICATED_ANONYMOUSLY }

        # application
        - { path: ^/login,   access: 'isAnonymous()' }
        - { path: ^/account, access: 'isAuthenticated()' }
        - { path: ^/fs-file, access: 'isAnonymous() || isAuthenticated()' }
        - { path: ^/fs-download, access: 'isAnonymous() || isAuthenticated()' }
        - { path: ^/fs, access: 'isAuthenticated()' }
        - { path: ^/admin,   role: ROLE_ADMIN }
